/**
 * Generates and triggers download of a PDF containing the tailored resume text.
 * @param {string} tailoredText - The text generated by Gemini.
 */
function generatePdf(tailoredText) {
  const { jsPDF } = window.jspdf;
  const doc = new jsPDF();

  const margin = 15;
  const pageHeight = doc.internal.pageSize.height;
  const pageWidth = doc.internal.pageSize.width;
  const maxLineWidth = pageWidth - margin * 2;
  
  doc.setFont("helvetica", "normal");
  doc.setFontSize(11);

  // jsPDF handles splitting text into lines based on width
  const lines = doc.splitTextToSize(tailoredText, maxLineWidth);
  
  let currentY = margin;
  const lineHeight = 6; // slightly larger than default for readability

  lines.forEach(line => {
    // If the line exceeds the page height, create a new page
    if (currentY + lineHeight > pageHeight - margin) {
      doc.addPage();
      currentY = margin;
    }
    doc.text(line, margin, currentY);
    currentY += lineHeight;
  });

  // Automatically trigger download
  doc.save('Tailored_Resume.pdf');
}
